version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: ${DB_USER}
      DB_SERVER: ${DB_SERVER}
      DEV_DB_SERVER: ${DEV_DB_SERVER}
      TEST_DB_SERVER: ${TEST_DB_SERVER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      FLASK_ENV: ${FLASK_ENV}
    command: 'flask run --host=0.0.0.0 --port=5000'
    ports:
      - 8000:5000
    volumes:
      - .:/app
    depends_on:
      - db

#THIS WILL BE UNCOMMENTED FOR QUEUEING
#  queue:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: 'python -u /app/consumer.py'
#    restart: always
#    depends_on:
#      - db

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - .dbdata:/var/lib/postgres
    ports:
      - 5430:5432
